### ISSUE TITLE
Types support

### ISSUE THREAD

**Issue by dineshbvadhia** [chicago-cdac/lmdb-dict#2]
Hello again. Is there a history behind lmdb-dict specifically is it used in some uc-dsi systems?

Also, is Types support planned? If not, what is the suggestion if we are using mypy? Thanks

**Comment by jesteria** [comment]
So far I know I've used `lmdb-dict` in [Fate](https://github.com/internet-equity/fate), which in turn is the backend for the active project [Netrics](https://github.com/internet-equity/netrics).

For Fate, LMDB and `lmdb-dict` serve to store state across task runs. For example, in Netrics, a measurement task polls the number of devices connected to the local network and stores this datapoint to report trends. Similarly, multiple Internet speed measurements intend to store their bandwidth consumption under a shared key, such that they may disable themselves if they've used too much bandwidth within a month.

The dictionary interface of `lmdb-dict` is both convenient for development of these features and will enable its use in user-facing configuration, whereby users of Netrics might write such simple Boolean conditions against the database dictionary.

---

As for types and mypy, I think that would be great! But no I have no immediate plans for this enhancement.

I would encourage anyone interested in adding this to open a PR.

Otherwise, I don't know that this library's lack of type annotations need be a problem for mypy users. Indeed the `__getitem__` method of the serializing interface can return objects of `Any` type, regardless. Is there a particular case in which this is a problem for your code? I would think that if your code handles particular types, that this could be annotated there, (in a purpose-built wrapper function or otherwise).
